USE DATABASE BANKING_ANALYTICS_DB;
USE SCHEMA BANKING;
USE WAREHOUSE COMPUTE_WH;

CREATE OR REPLACE FILE FORMAT BANKING_CSV_FORMAT
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('', 'NULL')
    EMPTY_FIELD_AS_NULL = TRUE;

CREATE OR REPLACE STAGE BANKING_STAGE
    FILE_FORMAT = BANKING_CSV_FORMAT;

CREATE OR REPLACE STAGE BANKING_STAGE
    FILE_FORMAT = BANKING_CSV_FORMAT;

USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE STORAGE INTEGRATION BANKING_S3_INTEGRATION
    TYPE = EXTERNAL_STAGE
    STORAGE_PROVIDER = 'S3'
    ENABLED = TRUE
    STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::918106143346:role/snowflake-banking-role'
    STORAGE_ALLOWED_LOCATIONS = (
        's3://banking-analytics-project/banking/processed/'
    );

DESC INTEGRATION BANKING_S3_INTEGRATION;

CREATE OR REPLACE STAGE BANKING_S3_STAGE
    URL = 's3://banking-analytics-project/banking/processed/'
    STORAGE_INTEGRATION = BANKING_S3_INTEGRATION
    FILE_FORMAT = BANKING_CSV_FORMAT;

LIST @BANKING_S3_STAGE;

COPY INTO BANK_TRANSACTIONS
FROM @BANKING_S3_STAGE/bank_transactions_cleaned.csv
FILE_FORMAT = (FORMAT_NAME = BANKING_CSV_FORMAT)
VALIDATION_MODE = 'RETURN_ERRORS';

COPY INTO BANK_TRANSACTIONS
FROM @BANKING_S3_STAGE/bank_transactions_cleaned.csv
FILE_FORMAT = (FORMAT_NAME = BANKING_CSV_FORMAT);

SELECT COUNT(*) AS TOTAL_ROWS
FROM BANK_TRANSACTIONS;

SELECT *
FROM BANK_TRANSACTIONS
LIMIT 10;